server:
  port: 8080

okta:
  oauth2:
    issuer: https://${OKTA_ORG_DOMAIN:trial-3347400.okta.com}/oauth2/default
idp:
  okta:
    client-id: ${OKTA_CLIENT_ID:0oahotvh7k4Sf41BL697}
    client-secret: ${OKTA_CLIENT_SECRET:nuVBp8Pg9ddDeCV5aoTC9ZnflGScV668iSXYM1AlPGjrKfqkL26yQ1CHNXvP0_Em}
    scope: ${OKTA_SCOPE:openid profile email offline_access}
    grant-type: ${GRANT_TYPE:password}
    domain: https://${OKTA_ORG_DOMAIN:trial-3347400.okta.com}
    token: ${OKTA_TOKEN:0074Xwdf8Sy2ocovgtx_dT1GWtDgEI7Yhd1X6PQ48I}
gcp:
  bucket-name: "bucketerria"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    url: jdbc:postgresql:///${DB_DATABASE_NAME:postgres}
    hikari:
      datasource-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DB_CLOUD_SQL_INSTANCE:decisive-unison-430919-k4:europe-central2:learning-center-db}
        enableIamAuth: true
        sslmode: disable
  flyway:
    locations: db.migration
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  freemarker.cache: false
  thymeleaf.cache: false
  groovy.template.cache: false
#security:
#  jwt:
#    access-token-expiration: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRATION:36000000}
#    refresh-token-expiration: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:864000000}
#    signing-key: ${SECURITY_JWT_SIGNING_KEY:24432646294A404E635266556A586E5A7234753778214125442A472D4B615064}
#
#
