server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql:///${DB_DATABASE_NAME}
    hikari:
      datasource-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DB_CLOUD_SQL_INSTANCE}
  flyway:
    locations: db.migration
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  freemarker.cache: false
  thymeleaf.cache: false
  groovy.template.cache: false
security:
  jwt:
    access-token-expiration: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRATION:36000000}
    refresh-token-expiration: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:864000000}
    signing-key: ${SECURITY_JWT_SIGNING_KEY:24432646294A404E635266556A586E5A7234753778214125442A472D4B615064}
